name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: 84.247.129.116
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Add ServerAliveInterval to keep the SSH connection alive
          echo "ServerAliveInterval 60" >> /etc/ssh/ssh_config
          echo "ServerAliveCountMax 100" >> /etc/ssh/ssh_config

          cd /home/zoomblie
          git fetch origin main
          git reset --hard origin/main
          docker compose down
          
          # Timeout for the build command
          timeout 20m docker compose build --no-cache

          docker compose up -d
