name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    timeout-minutes: 120  # Extend the job timeout to 2 hours

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: 84.247.129.116
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Add ServerAliveInterval to keep the SSH connection alive
          echo "ServerAliveInterval 60" >> /etc/ssh/ssh_config
          echo "ServerAliveCountMax 100" >> /etc/ssh/ssh_config

          # Ensure Docker is in the right directory
          cd /home/zoomblie
          git fetch origin main
          git reset --hard origin/main
          

          # Start building with a timeout of 20 minutes and add periodic output to prevent inactivity timeout
          timeout 20m bash -c "
            while true; do
              echo 'Building Docker images...'
              sleep 30  # Output every 30 seconds
            done &
            docker compose build --no-cache
          "
          docker compose down
          docker compose up -d
